# Site Settings
lang: en
title: PISM
tagline: Parallel Ice Sheet Model
email: your-email@domain.com
description: >
  Demo site for PISM, the Parallel Ice Sheet Model
baseurl: "/pism_website_test"
url: "https://juliusgarbe.github.io/pism_website_test"
twitter_username: pism
github_username:  pism
permalink: pretty
favicon: /favicon.ico
gh_sponsor: 
#hide_share_buttons: true
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
#theme_color: '#64A5C8'
fixed_navbar: top

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 

# SEO
author: 
  twitter: chrisrhymes
lang: en_GB
logo: /img/avatar.png
twitter:
  username: chrisrhymes
  card: summary_large_image
facebook:
  publisher: https://www.facebook.com/CS-Rhymes-1423568567916115
social:
  name: C.S. Rhymes
  links:
    - https://www.twitter.com/chrisrhymes
    - https://www.facebook.com/CS-Rhymes-1423568567916115
    - https://github.com/chrisrhymes

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: #example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
